name: ✨ Feature Request
description: Suggest an idea for Kosmic Lab
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Core Functionality (K-Index, metrics)
        - Performance & Optimization
        - Documentation
        - Testing & Quality
        - User Experience
        - API & Integrations
        - Visualization & Dashboards
        - Deployment & Infrastructure
        - AI & Automation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my work
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I am working on...
        This feature would help me to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide example code or usage
      placeholder: |
        ```python
        # Example of how the feature would be used
        from kosmic_lab import new_feature
        result = new_feature(params)
        ```
      render: python

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What are the expected benefits of this feature?
      placeholder: |
        - Faster computation
        - Easier workflow
        - Better insights

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how this could be implemented?
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute?
      options:
        - label: I am willing to help implement this feature
        - label: I can provide testing/feedback
        - label: I can help with documentation

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups
      placeholder: Additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly described the problem and solution
          required: true
        - label: I have checked the VISION.md roadmap
          required: false
        - label: This aligns with Kosmic Lab's core values (reproducibility, rigor, openness)
          required: true
